/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addCustomer.java
 *
 * Created on Jul 6, 2017, 9:52:58 AM
 */
package car.show.pkg12;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Yoofiyaapa
 */
public class addCustomer extends javax.swing.JFrame {

    /** Creates new form addCustomer */
    public addCustomer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        phn = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ad = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Customer");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Customer Details Entry Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 20, 360, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Customer ID * :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 100, 143, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Name *:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 180, 76, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("Address :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 240, 127, 27);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setText("Phone NO *:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 420, 127, 34);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("Email ID :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 490, 118, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setText("*Mandatory");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(65, 686, 108, 34);

        id.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(id);
        id.setBounds(540, 100, 310, 28);

        name.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(name);
        name.setBounds(540, 180, 370, 28);

        phn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(phn);
        phn.setBounds(540, 410, 320, 28);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(830, 570, 107, 37);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("HOME PAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 570, 200, 31);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("ADD CUSTOMER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 570, 180, 37);

        email.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(email);
        email.setBounds(550, 470, 390, 28);

        ad.setColumns(20);
        ad.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        ad.setRows(5);
        jScrollPane1.setViewportView(ad);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(540, 250, 440, 116);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/13.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1010, 650);

        setSize(new java.awt.Dimension(1026, 684));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
new addCustomer().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String memID, memName, address,memNO,memEmail;
memID=id.getText();
memName=name.getText();
address=ad.getText();
memNO=phn.getText();
memEmail=email.getText();
try
{ Class.forName("java.sql.DriverManager");
Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/carshowroom","root","root");
Statement stmt=con.createStatement();
 stmt.executeUpdate("insert into Customer(Customer_ID, Name, Address, Phone_NO, Email_ID, Date) values('"+memID+"','"+memName+"','"+address+"','"+memNO+"','"+memEmail+"',curdate())");
 JOptionPane.showMessageDialog(this, "Customer added successfully");}
catch(Exception e)
{ JOptionPane.showMessageDialog(this, e.getMessage()); }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();
new Welcome().setVisible(true); 

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new addCustomer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ad;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phn;
    // End of variables declaration//GEN-END:variables
}
