/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addOrder.java
 *
 * Created on Jul 8, 2017, 11:41:03 PM
 */
package car.show.pkg12;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Yoofiyaapa
 */
public class addOrder extends javax.swing.JFrame {

    /** Creates new form addOrder */
    public addOrder() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        orderNO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cusID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cusName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cusPhn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        carID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        carName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cash = new javax.swing.JRadioButton();
        net = new javax.swing.JRadioButton();
        card = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        amt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add ORDER");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("CAR Order Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 30, 294, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Order NO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(29, 114, 107, 47);

        orderNO.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        orderNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderNOActionPerformed(evt);
            }
        });
        getContentPane().add(orderNO);
        orderNO.setBounds(202, 123, 114, 28);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("Customer ID :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(29, 201, 127, 22);

        cusID.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        cusID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cusIDMouseClicked(evt);
            }
        });
        cusID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusIDActionPerformed(evt);
            }
        });
        getContentPane().add(cusID);
        cusID.setBounds(202, 198, 162, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("Customer Name:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(29, 272, 152, 22);

        cusName.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(cusName);
        cusName.setBounds(210, 270, 232, 28);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setText("Customer Phone NO:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 350, 190, 22);

        cusPhn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(cusPhn);
        cusPhn.setBounds(230, 350, 215, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Date :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(560, 120, 85, 22);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTextField2.setText("9 July 2016");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(750, 120, 148, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setText("Car ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(560, 190, 59, 22);

        carID.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        carID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carIDActionPerformed(evt);
            }
        });
        getContentPane().add(carID);
        carID.setBounds(760, 190, 155, 28);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setText("Car Name:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(560, 270, 102, 22);

        carName.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        carName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carNameActionPerformed(evt);
            }
        });
        getContentPane().add(carName);
        carName.setBounds(740, 260, 243, 28);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setText("Price:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(570, 350, 53, 22);

        price.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(price);
        price.setBounds(730, 340, 243, 28);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mode of Payment:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 430, 245, 29);

        buttonGroup1.add(cash);
        cash.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        cash.setText("Cash(5%)");
        getContentPane().add(cash);
        cash.setBounds(400, 430, 119, 31);

        buttonGroup1.add(net);
        net.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        net.setText("Net Banking(8%)");
        getContentPane().add(net);
        net.setBounds(610, 430, 185, 31);

        buttonGroup1.add(card);
        card.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        card.setText("Credit Card(6.5%)");
        getContentPane().add(card);
        card.setBounds(830, 430, 193, 31);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bill Amount:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(80, 510, 147, 29);

        amt.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        getContentPane().add(amt);
        amt.setBounds(330, 510, 200, 35);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Bill Transaction.....");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(670, 510, 201, 31);

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton5.setText("Total Amount");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(90, 590, 180, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("ADD Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 670, 160, 31);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setText("HOME PAGE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(520, 590, 170, 31);

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(760, 670, 120, 31);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/sc2.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1080, 750);

        setBounds(0, 0, 1095, 788);
    }// </editor-fold>//GEN-END:initComponents

    private void orderNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderNOActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_orderNOActionPerformed

    private void cusIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusIDMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_cusIDMouseClicked

    private void cusIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusIDActionPerformed
String p=null;
        String id=cusID.getText(); 
try{
    Class.forName("java.sql.DriverManager");
    Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/carshowroom","root","root");
    Statement stmt=con.createStatement();
   String q =  "select * from Customer where Customer_ID = '"+id+"';";
   ResultSet rs=stmt.executeQuery(q);
   if(rs.next())
   { 
       String name=rs.getString("Name");
       String phn=rs.getString("Phone_NO");
       cusName.setText(name);
       cusPhn.setText(phn);
       p="ss";
      }
   if  (p == null){
                JOptionPane.showMessageDialog(this,"Member not found!");
   }
}
catch(Exception e)
{  JOptionPane.showMessageDialog(this, e.getMessage()); }
}//GEN-LAST:event_cusIDActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

    private void carIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carIDActionPerformed
String a=null;
String cid=carID.getText();
try{ 
    Class.forName("java.sql.DriverManager");
    Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/carshowroom","root","root");
    Statement stmt=con.createStatement();
    String q= "Select*from Car_info where Car_ID = '"+cid+"';";
    ResultSet rs=stmt.executeQuery(q);
    if(rs.next())
    {
        String name=rs.getString("Car_Name");
        String Price=rs.getString("Price");
        carName.setText(name);
        price.setText(Price);
        a="ss";
    }
    if (a==null){
        JOptionPane.showMessageDialog(this," Car not Found! ");
        
    }
}
catch(Exception e)
{ JOptionPane.showMessageDialog(this, e.getMessage());}
   
// TODO add your handling code here:
}//GEN-LAST:event_carIDActionPerformed

    private void carNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carNameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_carNameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
new Welcome().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
dispose();
new addOrder().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Double pri,dis=0.0,amount=0.0,dispri;
pri=Double.parseDouble(price.getText());
if(cash.isSelected())
    dis=5.0;
else if(net.isSelected())
    dis=8.0;
else if(card.isSelected())
    dis=6.5;
dispri=(dis*pri)/100.0;
amount= ( pri - dispri );
amt.setText(Double.toString(amount));
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String cusname=cusName.getText();  
String carname=carName.getText();
int pri=Integer.parseInt(price.getText());
Double a=Double.parseDouble(amt.getText());
JOptionPane.showMessageDialog(this, "Customer Name :- " + cusname + "\n" + "Car Name :- " + carname + "\n" + "Car Price :- " + pri + "\n" + "Bill Amount :- " + a + "\n" + "THANK YOU VISIT AGAIN" );
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String cust, car;
int odr1=Integer.parseInt(orderNO.getText());
cust=cusName.getText();
car=carName.getText();
String carp=price.getText();
String bill=amt.getText();
try
{ Class.forName("java.sql.DriverManager");
Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/carshowroom","root","root");
Statement stmt=con.createStatement();
 stmt.executeUpdate("insert into orderlist values('"+odr1+"','"+cust+"','"+car+"','"+carp+"','"+bill+"')");
 JOptionPane.showMessageDialog(this, "Order added successfully");}
catch(Exception e)
{ JOptionPane.showMessageDialog(this, e.getMessage()); }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new addOrder().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField carID;
    private javax.swing.JTextField carName;
    private javax.swing.JRadioButton card;
    private javax.swing.JRadioButton cash;
    private javax.swing.JTextField cusID;
    private javax.swing.JTextField cusName;
    private javax.swing.JTextField cusPhn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton net;
    private javax.swing.JTextField orderNO;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
