/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car.show.pkg12;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Yoofiyaapa
 */
public class cardet extends javax. swing.JFrame {

    /**
     * Creates new form cardet
     */
    public cardet() {
        initComponents();  v.setVisible(false);
        i10.setVisible(false);
        
        elantra.setVisible(false); 
        
        verna.setVisible(false);
        
        creta.setVisible(false);
        
        tucson.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        v = new javax.swing.JLabel();
        i10 = new javax.swing.JComboBox<>();
        elantra = new javax.swing.JComboBox<>();
        verna = new javax.swing.JComboBox<>();
        creta = new javax.swing.JComboBox<>();
        tucson = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        e = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        var = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Details");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  CAR DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(392, 34, 183, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Car Name:-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(63, 98, 104, 22);

        a.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(255, 95, 211, 28);

        v.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        v.setForeground(new java.awt.Color(255, 255, 255));
        v.setText("Variant:- ");
        getContentPane().add(v);
        v.setBounds(560, 130, 86, 22);

        i10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        i10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.2 CRDi Era (Diesel)", "1.2 Kappa Era (Petrol)", "1.2 CRDi Sportz (Diesel)", "1.2 Kappa Sportz (Petrol)" }));
        getContentPane().add(i10);
        i10.setBounds(690, 90, 340, 28);

        elantra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        elantra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.6 S (Diesel)", "2.0 S (Petrol)", "1.6 SX (Diesel)", "2.0 SX (Petrol)" }));
        getContentPane().add(elantra);
        elantra.setBounds(690, 90, 340, 30);

        verna.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        verna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.6 S (Diesel)", "2.0 S (Petrol)", "1.6 SX (Diesel)", "1.6 SX (Petrol)" }));
        getContentPane().add(verna);
        verna.setBounds(690, 90, 340, 30);

        creta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        creta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.6 CRDi SX (Diesel)", "1.6 CRDi SX (Petrol)" }));
        creta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cretaActionPerformed(evt);
            }
        });
        getContentPane().add(creta);
        creta.setBounds(690, 90, 340, 30);

        tucson.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tucson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2WD GL (Diesel)", "2WD GL (Petrol)" }));
        getContentPane().add(tucson);
        tucson.setBounds(690, 90, 340, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ex-Showroom Price");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 200, 250, 40);

        b.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(b);
        b.setBounds(580, 200, 240, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Engine");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 280, 120, 20);

        c.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(c);
        c.setBounds(580, 270, 240, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mileage");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 350, 130, 20);

        d.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(d);
        d.setBounds(580, 340, 240, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Max Torque");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 410, 130, 20);

        e.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(e);
        e.setBounds(580, 400, 240, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("GET DETAILS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 460, 180, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(580, 460, 100, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("HOME PAGE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(930, 460, 150, 31);

        var.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(var);
        var.setBounds(690, 140, 340, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/sc4.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1110, 510);

        setBounds(0, 0, 1118, 547);
    }// </editor-fold>//GEN-END:initComponents

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
if(a.getText().equals("Grand i10"))
{i10.setVisible(true);
    v.setVisible(true);
    elantra.setVisible(false);
    creta.setVisible(false);
    verna.setVisible(false);
    tucson.setVisible(false);
    
    
    
}
else  if(a.getText().equals("Elantra"))
  { elantra.setVisible(true);
    v.setVisible(true);
    i10.setVisible(false);
    creta.setVisible(false);
    verna.setVisible(false);
    tucson.setVisible(false);
    
  }
else  if(a.getText().equals("Verna"))
  { elantra.setVisible(false);
    v.setVisible(true);
    i10.setVisible(false);
    creta.setVisible(false);
    verna.setVisible(true);
    tucson.setVisible(false);
    
  }
else  if(a.getText().equals("Creta"))
  { elantra.setVisible(false);
    v.setVisible(true);
    i10.setVisible(false);
    creta.setVisible(true);
    verna.setVisible(false);
    tucson.setVisible(false);
    
  }
else  if(a.getText().equals("Tucson"))
  { elantra.setVisible(false);
    v.setVisible(true);
    i10.setVisible(false);
    creta.setVisible(false);
    verna.setVisible(false);
    tucson.setVisible(true);
    
  }
    else 
    {JOptionPane.showMessageDialog(this, "NO CAR FOUND!");  }

    }//GEN-LAST:event_aActionPerformed

    private void cretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cretaActionPerformed
      
    }//GEN-LAST:event_cretaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

String v=var.getText();
String p=null;
        String name=a.getText(); 
try{
    Class.forName("java.sql.DriverManager");
    Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/carshowroom","root","root");
    Statement stmt=con.createStatement();
   String q =  " select * from carlist where Car_Name = '"+name+"' and Variant='"+v+"'";;
   ResultSet rs=stmt.executeQuery(q);
   if(rs.next())
   { 
       String price=rs.getString("Price");
       String eng=rs.getString("Engine");
       String mt=rs.getString("Max_Torque");
       String mil=rs.getString("Mileage");
       b.setText(price);
       c.setText(eng);
       d.setText(mil);
       e.setText(mt);
       p="ss";
      }
   if  (p == null){
                JOptionPane.showMessageDialog(this,"NO Details!");
   }
}
catch(Exception e)
{  JOptionPane.showMessageDialog(this, e.getMessage()); }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();
new cardet().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
new Welcome().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cardet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cardet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cardet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cardet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cardet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JComboBox<String> creta;
    private javax.swing.JTextField d;
    private javax.swing.JTextField e;
    private javax.swing.JComboBox<String> elantra;
    private javax.swing.JComboBox<String> i10;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> tucson;
    private javax.swing.JLabel v;
    private javax.swing.JTextField var;
    private javax.swing.JComboBox<String> verna;
    // End of variables declaration//GEN-END:variables
}
