/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * carList.java
 *
 * Created on Jul 6, 2017, 10:04:23 AM
 */
package car.show.pkg12;

/**
 *
 * @author Yoofiyaapa
 */
public class carList extends javax.swing.JFrame {

    /** Creates new form carList */
    public carList() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car list");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CARS:-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(34, 23, 224, 52);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("3. VERNA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(930, 100, 120, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CAR ID:- 11A ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(950, 140, 98, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PRICE:- Rs 11,50,000");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(950, 170, 180, 17);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/Grand i10 (2).png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 220, 360, 170);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("5. TUCSON");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(710, 450, 110, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("CAR ID:- 15A ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(730, 490, 98, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("PRICE:- Rs 27,57,000");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(730, 530, 180, 17);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/Elantra1.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(510, 210, 360, 190);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("2. ELANTRA");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(520, 100, 120, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("CAR ID:- 13A ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(530, 140, 98, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("PRICE:- Rs 10,00,000");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(530, 170, 180, 17);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/Verna (2).png"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(890, 220, 350, 170);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("1. GRAND i10");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(34, 102, 120, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("CAR ID:- 12B ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(56, 142, 98, 17);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("PRICE:- Rs 5,37,000");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(56, 177, 143, 17);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/Cretaq.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(200, 570, 320, 160);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("4. CRETA");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(210, 450, 81, 22);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("CAR ID:- 14B ");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(210, 490, 98, 17);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("PRICE:- Rs 20,90,000");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(210, 530, 180, 17);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/tucson m.png"))); // NOI18N
        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(730, 570, 360, 170);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("ADD CAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 750, 210, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("HOME PAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1060, 770, 170, 40);

        setBounds(0, 0, 1273, 871);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
new addCar().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();
new Welcome().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new carList().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
