/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Elantra.java
 *
 * Created on Jul 31, 2017, 11:05:22 PM
 */
package car.show.pkg12;

import javax.swing.JOptionPane;

/**
 *
 * @author Yoofiyaapa
 */
public class Elantra extends javax.swing.JFrame {

    /** Creates new form Elantra */
    public Elantra() {
        initComponents();
        w.setVisible(false);
        b.setVisible(true);
        bk.setVisible(false);
        s.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        e1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        e2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        e3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        v = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        bl = new javax.swing.JRadioButton();
        si = new javax.swing.JRadioButton();
        ba = new javax.swing.JRadioButton();
        wh = new javax.swing.JRadioButton();
        s = new javax.swing.JLabel();
        bk = new javax.swing.JLabel();
        w = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        a1 = new javax.swing.JCheckBox();
        a2 = new javax.swing.JCheckBox();
        a3 = new javax.swing.JCheckBox();
        a4 = new javax.swing.JCheckBox();
        a5 = new javax.swing.JCheckBox();
        a6 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elantra");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Elantra");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 191, 53);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("PRODUCT DETAILS-->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 20, 235, 31);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Choose a Engine....");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 173, 22);

        buttonGroup1.add(e1);
        e1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e1.setText("U2 1.6 Diesel 6 Speed Manual Transmission");
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        getContentPane().add(e1);
        e1.setBounds(30, 120, 415, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("4-DOOR Diesel 6 Speed Manual Transmission");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 160, 359, 22);

        buttonGroup1.add(e2);
        e2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e2.setText("U2 1.6 Diesel 6 Speed Automatic Transmission");
        getContentPane().add(e2);
        e2.setBounds(30, 190, 439, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("4-DOOR Diesel 6 Speed Automatic Transmission");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 230, 382, 22);

        buttonGroup1.add(e3);
        e3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e3.setText("NU 2.0 Petrol 6 Speed Manual Transmission");
        getContentPane().add(e3);
        e3.setBounds(30, 260, 417, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("4-DOOR Petrol 6 Speed Manual Transmission");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 300, 358, 22);

        b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/Elantra blue.png"))); // NOI18N
        getContentPane().add(b);
        b.setBounds(480, 70, 568, 243);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Choose a Variant..");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 350, 184, 31);

        v.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        v.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIX", "SIX(0)", "S" }));
        getContentPane().add(v);
        v.setBounds(40, 400, 125, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Choose A Exterior Color...");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 400, 230, 22);

        buttonGroup2.add(bl);
        bl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bl.setText("Marina Blue");
        bl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blActionPerformed(evt);
            }
        });
        getContentPane().add(bl);
        bl.setBounds(610, 400, 133, 31);

        buttonGroup2.add(si);
        si.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        si.setText("Sleek Silver");
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });
        getContentPane().add(si);
        si.setBounds(770, 400, 129, 31);

        buttonGroup2.add(ba);
        ba.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ba.setText("Phantom Black");
        ba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baActionPerformed(evt);
            }
        });
        getContentPane().add(ba);
        ba.setBounds(610, 450, 161, 31);

        buttonGroup2.add(wh);
        wh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        wh.setText("Polar White");
        wh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whActionPerformed(evt);
            }
        });
        getContentPane().add(wh);
        wh.setBounds(780, 450, 131, 31);

        s.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/Elantra Silver.png"))); // NOI18N
        getContentPane().add(s);
        s.setBounds(470, 70, 620, 260);

        bk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/Elantra black.png"))); // NOI18N
        getContentPane().add(bk);
        bk.setBounds(470, 80, 600, 240);

        w.setIcon(new javax.swing.ImageIcon("E:\\CARS\\Elantra\\Elantra white.png")); // NOI18N
        getContentPane().add(w);
        w.setBounds(470, 80, 640, 270);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Choose Accessories...");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 460, 230, 22);

        a1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        a1.setText("Seat cover-Jacquard");
        getContentPane().add(a1);
        a1.setBounds(30, 510, 170, 25);

        a2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        a2.setText("3M Anti Rust Coating");
        getContentPane().add(a2);
        a2.setBounds(210, 510, 173, 25);

        a3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        a3.setText("Front Font Lights");
        getContentPane().add(a3);
        a3.setBounds(30, 580, 180, 25);

        a4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        a4.setText("MapmyIndia GPS Navigation");
        getContentPane().add(a4);
        a4.setBounds(400, 510, 221, 25);

        a5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        a5.setText("Alloy Wheel");
        getContentPane().add(a5);
        a5.setBounds(450, 590, 130, 25);

        a6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        a6.setText("2 Din Infotainment System");
        getContentPane().add(a6);
        a6.setBounds(210, 590, 220, 25);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Rs 5400/-");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 550, 80, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Rs 4500/-");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 550, 90, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Rs 5550/-");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 610, 80, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Rs 16000/-");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(410, 550, 110, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Rs 22500/-");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(450, 620, 80, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Rs 14500/-");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(220, 620, 100, 17);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("RESULT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(780, 520, 110, 31);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setText("<--BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(660, 610, 130, 31);

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton4.setText("HOME PAGE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(890, 610, 150, 31);

        setSize(new java.awt.Dimension(1077, 710));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void blActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blActionPerformed
  w.setVisible(false);
        b.setVisible(true);
        bk.setVisible(false);
        s.setVisible(false);      // TODO add your handling code here:
    }//GEN-LAST:event_blActionPerformed

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
w.setVisible(false);
        b.setVisible(false);
        bk.setVisible(false);
        s.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_siActionPerformed

    private void baActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baActionPerformed
w.setVisible(false);
        b.setVisible(false);
        bk.setVisible(true);
        s.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_baActionPerformed

    private void whActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whActionPerformed
w.setVisible(true);
        b.setVisible(false);
        bk.setVisible(false);
        s.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_whActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String variant = null, engine = null,color = null,acc = null;
 if (e1.isSelected())
 engine="U2 1.6 Diesel 6 Speed Manual Transmission";    
else if (e2.isSelected())
engine="U2 1.6 Diesel 6 speed Automatic Transmission";
else if (e3.isSelected())
    engine="NU 2.0 Petrol 6 Speed Manual Transmission";
 
 if(a1.isSelected())
     acc= "Seat Cover - Jacquard    ";
  if(a2.isSelected())
     acc=acc+  "3M Anti Rust Coating     ";
   if(a3.isSelected())
     acc=acc + "Front Fog Lights     ";
    if(a4.isSelected())
     acc= acc + "MapmyIndia GPS Navigation      ";
     if(a5.isSelected())
     acc= acc + "Alloy Wheel";
      if(a6.isSelected())
     acc= acc + "2 Din Infotainment System    ";
     
     
 
 
 
if (v.getSelectedIndex()==0)
   variant=" SIX " ;
else if (v.getSelectedIndex()==1)
   variant=" SIX(O) " ;
else if (v.getSelectedIndex()==2)
   variant=" S " ;
if(wh.isSelected())
 color="Pure White"; 
else if(si.isSelected())
color="Sleek Silver"; 
else if(bl.isSelected())
color="Marina Blue"; 
else if(ba.isSelected())
color="Phantom Black"; 

JOptionPane.showMessageDialog(this, " MODEL NAME :- ELANTRA " + "\n" +
        " VARIANT :- " + variant + "\n" +
          " ENGINE :- " + engine + "\n" +
        " EXTERIOR COLOR :- " + color + "\n" + 
        " ACCESSORIES :- " + acc + "\n" +
        " CONGRATS ! Your Vehicle Has Been Completed ");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
new buildCar().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
dispose();
new Welcome().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
new elantradet1().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Elantra().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox a1;
    private javax.swing.JCheckBox a2;
    private javax.swing.JCheckBox a3;
    private javax.swing.JCheckBox a4;
    private javax.swing.JCheckBox a5;
    private javax.swing.JCheckBox a6;
    private javax.swing.JLabel b;
    private javax.swing.JRadioButton ba;
    private javax.swing.JLabel bk;
    private javax.swing.JRadioButton bl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton e1;
    private javax.swing.JRadioButton e2;
    private javax.swing.JRadioButton e3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel s;
    private javax.swing.JRadioButton si;
    private javax.swing.JComboBox v;
    private javax.swing.JLabel w;
    private javax.swing.JRadioButton wh;
    // End of variables declaration//GEN-END:variables
}
