/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * i10.java
 *
 * Created on Jul 31, 2017, 11:05:12 PM
 */
package car.show.pkg12;

import javax.swing.JOptionPane;

/**
 *
 * @author Yoofiyaapa
 */
public class i10 extends javax.swing.JFrame {

    /** Creates new form i10 */
    public i10() {
        initComponents();
        white.setVisible(false);
        Red.setVisible(false);
        Black.setVisible(false);
        Blue.setVisible(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Silver = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        e1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        e2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vari = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cw = new javax.swing.JRadioButton();
        cb = new javax.swing.JRadioButton();
        cbl = new javax.swing.JRadioButton();
        cr = new javax.swing.JRadioButton();
        Black = new javax.swing.JLabel();
        white = new javax.swing.JLabel();
        Blue = new javax.swing.JLabel();
        Red = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        a1 = new javax.swing.JCheckBox();
        a2 = new javax.swing.JCheckBox();
        a3 = new javax.swing.JCheckBox();
        a4 = new javax.swing.JCheckBox();
        a5 = new javax.swing.JCheckBox();
        a6 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grand i10");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Grand i10");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 0, 212, 46);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("PRODUCT DETAILS -->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 64, 264, 32);

        Silver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/i10 white.png"))); // NOI18N
        getContentPane().add(Silver);
        Silver.setBounds(500, 60, 610, 240);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Choose a Engine...");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 127, 167, 22);

        buttonGroup1.add(e1);
        e1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e1.setText("1.2 Kappa Petrol 5- Speed Manual Transmission");
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        getContentPane().add(e1);
        e1.setBounds(10, 170, 455, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("5-DOOR Petrol 5 Speed Manual Transmission");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 220, 358, 22);

        buttonGroup1.add(e2);
        e2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e2.setText("1.2 U2 CRDi Diesel 5 Speed Manual Transmission");
        getContentPane().add(e2);
        e2.setBounds(10, 260, 463, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("5-DOOR Diesel 5 Speed Manual Transmission");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 310, 368, 26);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Choose a Variant..");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 370, 165, 22);

        vari.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ERA", "SPORTZ" }));
        getContentPane().add(vari);
        vari.setBounds(40, 430, 105, 28);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Choose a Exterior Color...");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 380, 241, 22);

        buttonGroup2.add(cw);
        cw.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cw.setText("Pure White");
        cw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cwActionPerformed(evt);
            }
        });
        getContentPane().add(cw);
        cw.setBounds(660, 370, 127, 31);

        buttonGroup2.add(cb);
        cb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cb.setText("Star Dust");
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        getContentPane().add(cb);
        cb.setBounds(890, 370, 109, 31);

        buttonGroup2.add(cbl);
        cbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbl.setText("Twilight Blue");
        cbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblActionPerformed(evt);
            }
        });
        getContentPane().add(cbl);
        cbl.setBounds(890, 430, 143, 31);

        buttonGroup2.add(cr);
        cr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cr.setText("Red Passion");
        cr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crActionPerformed(evt);
            }
        });
        getContentPane().add(cr);
        cr.setBounds(660, 420, 135, 31);

        Black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/i10 Black.png"))); // NOI18N
        getContentPane().add(Black);
        Black.setBounds(490, 40, 650, 270);

        white.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/i10 white.png"))); // NOI18N
        getContentPane().add(white);
        white.setBounds(520, 40, 610, 280);

        Blue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/i10 Blue.png"))); // NOI18N
        getContentPane().add(Blue);
        Blue.setBounds(520, 50, 600, 270);

        Red.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/i10 RED 1.png"))); // NOI18N
        getContentPane().add(Red);
        Red.setBounds(530, 40, 590, 280);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Choose Accessories...");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 450, 234, 26);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("RESULT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 510, 101, 31);

        a1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a1.setText("Seat Cover- Jacquard");
        getContentPane().add(a1);
        a1.setBounds(340, 490, 228, 31);

        a2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a2.setText("3M Anti Rust Coating");
        getContentPane().add(a2);
        a2.setBounds(600, 490, 221, 31);

        a3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a3.setText("Front Fog Lights");
        getContentPane().add(a3);
        a3.setBounds(860, 490, 169, 31);

        a4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a4.setText("MapmyIndia GPS Navigator");
        getContentPane().add(a4);
        a4.setBounds(600, 570, 273, 31);

        a5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a5.setText("Alloy Wheel");
        getContentPane().add(a5);
        a5.setBounds(890, 570, 131, 31);

        a6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a6.setText("2 Din Infotainment System");
        getContentPane().add(a6);
        a6.setBounds(330, 570, 269, 31);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Rs 5400/-");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 530, 71, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Rs 4500/-");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(610, 530, 71, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Rs 5550/-");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(860, 540, 71, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Rs 16000/-");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(620, 620, 80, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Rs 22500/-");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(910, 630, 80, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Rs 14500/-");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(360, 620, 80, 17);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setText("<-- BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(-130, 700, 117, 31);

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton4.setText("HOME PAGE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 590, 170, 31);

        setSize(new java.awt.Dimension(1136, 715));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
new i10det().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cwActionPerformed
Silver.setVisible(false);
white.setVisible(true);
Red.setVisible(false);
Black.setVisible(false);
Blue.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_cwActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
Silver.setVisible(false);
Black.setVisible(true);
white.setVisible(false);
Red.setVisible(false);
Blue.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_cbActionPerformed

    private void cblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblActionPerformed
Silver.setVisible(false);
white.setVisible(false);
Red.setVisible(false);
Black.setVisible(false);
Blue.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cblActionPerformed

    private void crActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crActionPerformed
Silver.setVisible(false);
white.setVisible(false);
Red.setVisible(true);
Black.setVisible(false);
Blue.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_crActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String variant = null, engine = null,color = null,acc = null;
 if (e1.isSelected())
 engine="1.2 Kappa Petrol 5- Speed Manual Transmission";    
else if (e2.isSelected())
engine="1.2 U2 CRDi Diesel 5 Speed Manual Transmission";
 
 if(a1.isSelected())
     acc= "Seat Cover - Jacquard    ";
  if(a2.isSelected())
     acc=acc+  "3M Anti Rust Coating     ";
   if(a3.isSelected())
     acc=acc + "Front Fog Lights     ";
    if(a4.isSelected())
     acc= acc + "MapmyIndia GPS Navigation      ";
     if(a5.isSelected())
     acc= acc + "Alloy Wheel";
      if(a6.isSelected())
     acc= acc + "2 Din Infotainment System    ";
     
     
 
 
 
if (vari.getSelectedIndex()==0)
   variant=" ERA " ;
else if (vari.getSelectedIndex()==1)
   variant=" SPORTZ " ;
if(cw.isSelected())
 color="Pure White"; 
else if(cb.isSelected())
color="Star Dust"; 
else if(cbl.isSelected())
color="Twilight Blue"; 
else if(cr.isSelected())
color="Red Passion"; 

JOptionPane.showMessageDialog(this, " MODEL NAME :- GRAND i10 " + "\n" +
        " VARIANT :- " + variant + "\n" +
          " ENGINE :- " + engine + "\n" +
        " EXTERIOR COLOR :- " + color + "\n" + 
        " ACCESSORIES :- " + acc + "\n" +
        " CONGRATS ! Your Vehicle Has Been Completed ");


// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_e1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
new buildCar().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
dispose();
new Welcome().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new i10().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Black;
    private javax.swing.JLabel Blue;
    private javax.swing.JLabel Red;
    private javax.swing.JLabel Silver;
    private javax.swing.JCheckBox a1;
    private javax.swing.JCheckBox a2;
    private javax.swing.JCheckBox a3;
    private javax.swing.JCheckBox a4;
    private javax.swing.JCheckBox a5;
    private javax.swing.JCheckBox a6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton cb;
    private javax.swing.JRadioButton cbl;
    private javax.swing.JRadioButton cr;
    private javax.swing.JRadioButton cw;
    private javax.swing.JRadioButton e1;
    private javax.swing.JRadioButton e2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox vari;
    private javax.swing.JLabel white;
    // End of variables declaration//GEN-END:variables
}
