 /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on Jul 6, 2017, 8:17:12 AM
 */
package car.show.pkg12;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Yoofiyaapa
 */
public class Login extends javax.swing.JFrame {


    private static class setVisible {

        public setVisible(boolean b) {
        }
    }
    private Component then;

    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        user = new javax.swing.JTextField();
        pas = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        pass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HYUNDAI CARSHOWROOM");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 20, 350, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOG IN TO CONTINUE.........");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 240, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOGIN ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 130, 140, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 190, 120, 22);

        reset.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        reset.setText("RESET");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetMouseEntered(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(760, 270, 108, 30);

        user.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(user);
        user.setBounds(390, 130, 260, 32);

        pas.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        pas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pasMouseClicked(evt);
            }
        });
        pas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasActionPerformed(evt);
            }
        });
        getContentPane().add(pas);
        pas.setBounds(390, 190, 260, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("SIGN UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 280, 130, 30);

        pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/car_tips.jpg"))); // NOI18N
        pass.setText("jLabel1");
        getContentPane().add(pass);
        pass.setBounds(0, 0, 890, 342);

        setSize(new java.awt.Dimension(890, 366));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasActionPerformed
String username=user.getText().toLowerCase();
String pa=new String(pas.getPassword());
try 
{ Class.forName("java.sql.DriverManager");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost/carshowroom","root","root");
Statement stmt=con.createStatement();
String query="Select*from sign_up where Email='"+username+"' and Password='"+pa+"';";
ResultSet rs=stmt.executeQuery(query);
while(rs.next())
{ String p=rs.getString("Password"); 
    if(p.equals(pa))
   { JOptionPane.showMessageDialog(this, "You have Successfully LOGIN");
     dispose();
  new Welcome().setVisible(true); } 
else  { JOptionPane.showMessageDialog(this, "Incorrect Username or Password"); }
}
}
catch(Exception e)
{ JOptionPane.showMessageDialog(this, e.getMessage()); }   
    }//GEN-LAST:event_pasActionPerformed

    private void resetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseEntered

// TODO add your handling code here:
    }//GEN-LAST:event_resetMouseEntered

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
   dispose();
new Login().setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_resetMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
new NewUser().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasMouseClicked
  // TODO add your handling code here:
    }//GEN-LAST:event_pasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pas;
    private javax.swing.JLabel pass;
    private javax.swing.JButton reset;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
