/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * testDrive.java
 *
 * Created on Jul 16, 2017, 3:28:07 AM
 */
package car.show.pkg12;

import javax.swing.JOptionPane;

/**
 *
 * @author Yoofiyaapa
 */
public class testDrive extends javax.swing.JFrame {

    /** Creates new form testDrive */
    public testDrive() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        sal = new javax.swing.JComboBox();
        nm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        eID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        state = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        veh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        newveh = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test Drive");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Request a Test Drive");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(18, 27, 419, 29);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 74, 1358, 10);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name*");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(81, 158, 101, 22);

        sal.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        sal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr.", "Mrs.", "Miss." }));
        getContentPane().add(sal);
        sal.setBounds(337, 155, 74, 28);

        nm.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(nm);
        nm.setBounds(486, 157, 294, 24);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email ID*");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(81, 226, 88, 22);

        eID.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(eID);
        eID.setBounds(337, 223, 335, 28);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mobile NO*");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(81, 294, 103, 22);

        phn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(phn);
        phn.setBounds(337, 291, 335, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("State*");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(81, 359, 58, 22);

        state.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        state.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Andaman & Nicobar Island", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chandigarh", "Chattisgarh", "Dadra and Nagar Haveli", "Daman and Diu", "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu & Kashmir", "Jharkhand", "Karnataka", "Kerala", "Lakshadweep Island", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Orissa", "Pondicherry", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", " " }));
        getContentPane().add(state);
        state.setBounds(337, 356, 335, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("City*");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(81, 432, 45, 22);

        city.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(city);
        city.setBounds(337, 429, 335, 28);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Current Vehicle");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(81, 497, 141, 22);

        veh.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(veh);
        veh.setBounds(337, 494, 335, 28);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Model Interested In*");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(81, 572, 192, 22);

        newveh.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(newveh);
        newveh.setBounds(345, 572, 318, 28);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Comment");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(800, 200, 101, 22);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(710, 240, 270, 126);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(770, 510, 150, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(70, 640, 130, 31);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setText("HOME PAGE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(850, 650, 141, 31);

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton4.setText("BACK TO CAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(270, 640, 178, 35);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/show/pkg12/h1.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1200, 700);

        setSize(new java.awt.Dimension(1038, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String sal1 = null,state1 = null;
String name=nm.getText(); 
String email=eID.getText(); 
String mNO=phn.getText(); 
String newcar=newveh.getText(); 
if(sal.getSelectedIndex()==0)
   sal1 ="MR.";
else if(sal.getSelectedIndex()==1)
  sal1 ="MRS.";
else if(sal.getSelectedIndex()==2)
  sal1 ="MISS.";
if(state.getSelectedIndex()==0)
   state1 ="Andaman & Nicobar Islands";
else if(state.getSelectedIndex()==1)
   state1 ="Andhra Pradesh";
else if(state.getSelectedIndex()==2)
   state1 ="Arunachal Pradesh";
else if(state.getSelectedIndex()==3)
   state1 ="Assam";
else if(state.getSelectedIndex()==4)
   state1 ="Bihar";
else if(state.getSelectedIndex()==5)
   state1 ="Chandigarh";
else if(state.getSelectedIndex()==6)
   state1 ="Chattisgarh";
else if(state.getSelectedIndex()==7)
   state1 ="Dadra and Nagar Haveli";
else if(state.getSelectedIndex()==8)
   state1 ="Daman and Diu";
else if(state.getSelectedIndex()==9)
   state1 ="Delhi";
else if(state.getSelectedIndex()==10)
   state1 ="Goa";
else if(state.getSelectedIndex()==11)
   state1 ="Gujarat";
else if(state.getSelectedIndex()==12)
   state1 ="Haryana";
else if(state.getSelectedIndex()==13)
   state1 ="Himachal Pradesh";
else if(state.getSelectedIndex()==14)
   state1 ="Jammmu and Kashmir";
else if(state.getSelectedIndex()==15)
   state1 ="Jharkhand";
else if(state.getSelectedIndex()==16)
   state1 ="Karnataka";
else if(state.getSelectedIndex()==17)
   state1 ="Kerala";
else if(state.getSelectedIndex()==18)
   state1 ="Lakshadweep Island";
else if(state.getSelectedIndex()==19)
   state1 ="Madhya Pradesh";
else if(state.getSelectedIndex()==20)
   state1 ="Maharashtra";
else if(state.getSelectedIndex()==21)
   state1 ="Manipur";
else if(state.getSelectedIndex()==22)
   state1 ="Meghalaya";
else if(state.getSelectedIndex()==23)
   state1 ="Mizoram";
else if(state.getSelectedIndex()==24)
   state1 ="Nagaland";
else if(state.getSelectedIndex()==25)
   state1 ="Orissa";
else if(state.getSelectedIndex()==26)
   state1 ="Pondicherry";
else if(state.getSelectedIndex()==27)
   state1 ="Punjab";
else if(state.getSelectedIndex()==28)
   state1 ="Rajasthan";
else if(state.getSelectedIndex()==29)
   state1 ="Sikkim";
else if(state.getSelectedIndex()==30)
   state1 ="Tamil Nadu";
else if(state.getSelectedIndex()==31)
   state1 ="Telengana";
else if(state.getSelectedIndex()==32)
   state1 ="Tripura";
else if(state.getSelectedIndex()==33)
   state1 ="Uttar Pradesh";
else if(state.getSelectedIndex()==34)
   state1 ="Uttarakhand";
else if(state.getSelectedIndex()==35)
   state1 ="West Bengal";
String City=city.getText();
JOptionPane.showMessageDialog(null, "Thank You for registering with Hyundai. Our Customer Care representative will contact you shortly.");

System.out.println( "DETAILS" + "\n" +"Name : " + sal1 + name + "\n" + "Email ID : " + email + "\n" + " Mobile No : " + mNO + "\n" + "State : " + state1 +"\n" + "City : "+ City + "\n" + "Model :" + newcar );

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();
new testDrive().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
new Welcome().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
dispose();
new buildCar().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new testDrive().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField city;
    private javax.swing.JTextField eID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField newveh;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField phn;
    private javax.swing.JComboBox sal;
    private javax.swing.JComboBox state;
    private javax.swing.JTextField veh;
    // End of variables declaration//GEN-END:variables
}
