/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * viewCar.java
 *
 * Created on Jul 6, 2017, 9:53:25 AM
 */
package car.show.pkg12;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yoofiyaapa
 */
public class viewCar extends javax.swing.JFrame {

    /** Creates new form viewCar */
    public viewCar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Car");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36));
        jLabel1.setText("Car Details");

        cartbl.setFont(new java.awt.Font("Tahoma", 3, 18));
        cartbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car ID", "Car Name", "Manufacturer", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartbl.setRowHeight(25);
        cartbl.setRowMargin(6);
        jScrollPane1.setViewportView(cartbl);
        cartbl.getColumnModel().getColumn(0).setMinWidth(120);
        cartbl.getColumnModel().getColumn(0).setPreferredWidth(120);
        cartbl.getColumnModel().getColumn(0).setMaxWidth(120);
        cartbl.getColumnModel().getColumn(3).setMinWidth(120);
        cartbl.getColumnModel().getColumn(3).setPreferredWidth(200);
        cartbl.getColumnModel().getColumn(3).setMaxWidth(250);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 24));
        jButton1.setText("Fetch List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 24));
        jButton2.setText("Back To Main");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-993)/2, (screenSize.height-570)/2, 993, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 DefaultTableModel mdl = (DefaultTableModel) cartbl.getModel();
        int rowCount = mdl.getRowCount();
        for (int i=1; i<=rowCount; i++){
            mdl.removeRow(0);
        }
            try{
            Class.forName("java.sql.DriverManager");
            Connection con =(Connection) DriverManager.getConnection ("jdbc:mysql://localhost/carshowroom","root","root");
            Statement stmt = con.createStatement();
            String q = "select * from Car_info;",tr=null;
            ResultSet rs = stmt.executeQuery(q);
            while (rs.next()){
                String a,b,c,d;
                a = rs.getString("Car_ID");
                b = rs.getString("Car_Name");
                c = rs.getString("Manufacturer");
                d = rs.getString("Price");
               
                Object data[] = {a,b,c,d,};
                mdl.addRow(data);
                tr = "ss";
            }
            if (tr == null){
                JOptionPane.showMessageDialog(this,"No details found.");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();
new Welcome().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new viewCar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cartbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
