/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * viewCustomer.java
 *
 * Created on Jul 6, 2017, 9:53:36 AM
 */
package car.show.pkg12;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yoofiyaapa
 */
public class viewCustomer extends javax.swing.JFrame {

    /** Creates new form viewCustomer */
    public viewCustomer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        custbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CUSTOMER DETAILS");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("CUSTOMER DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(618, 18, 271, 34);

        custbl.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        custbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Address", "Phone NO", "Email ID", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        custbl.setAlignmentX(0.8F);
        custbl.setAlignmentY(0.8F);
        custbl.setRowHeight(50);
        custbl.setRowMargin(5);
        jScrollPane1.setViewportView(custbl);
        if (custbl.getColumnModel().getColumnCount() > 0) {
            custbl.getColumnModel().getColumn(0).setMinWidth(100);
            custbl.getColumnModel().getColumn(0).setPreferredWidth(100);
            custbl.getColumnModel().getColumn(0).setMaxWidth(100);
            custbl.getColumnModel().getColumn(1).setMinWidth(170);
            custbl.getColumnModel().getColumn(1).setPreferredWidth(170);
            custbl.getColumnModel().getColumn(2).setMinWidth(400);
            custbl.getColumnModel().getColumn(2).setPreferredWidth(400);
            custbl.getColumnModel().getColumn(3).setMinWidth(200);
            custbl.getColumnModel().getColumn(3).setPreferredWidth(200);
            custbl.getColumnModel().getColumn(3).setMaxWidth(200);
            custbl.getColumnModel().getColumn(4).setMinWidth(270);
            custbl.getColumnModel().getColumn(4).setPreferredWidth(270);
            custbl.getColumnModel().getColumn(5).setMinWidth(150);
            custbl.getColumnModel().getColumn(5).setPreferredWidth(150);
            custbl.getColumnModel().getColumn(5).setMaxWidth(150);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 63, 1391, 402);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton1.setText("Fetch List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 500, 230, 37);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton2.setText("HOME PAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(780, 510, 222, 37);

        setSize(new java.awt.Dimension(1417, 596));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DefaultTableModel mdl = (DefaultTableModel) custbl.getModel();
        int rowCount = mdl.getRowCount();
        for (int i=1; i<=rowCount; i++){
            mdl.removeRow(0);
        }
            try{
            Class.forName("java.sql.DriverManager");
            Connection con =(Connection) DriverManager.getConnection ("jdbc:mysql://localhost/carshowroom","root","root");
            Statement stmt = con.createStatement();
            String q = "select * from Customer;",tr=null;
            ResultSet rs = stmt.executeQuery(q);
            while (rs.next()){
                String a,b,c,d,e ,f;
                a = rs.getString("Customer_ID");
                b = rs.getString("Name");
                c = rs.getString("Address");
                d = rs.getString("Phone_No");
                e = rs.getString("Email_ID");
                f = rs.getString("Date");
                Object data[] = {a,b,c,d,e,f};
                mdl.addRow(data);
                tr = "ss";
            }
            if (tr == null){
                JOptionPane.showMessageDialog(this,"No details found.");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();
new Welcome().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new viewCustomer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable custbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
