/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * viewOrder.java
 *
 * Created on Jul 6, 2017, 9:54:45 AM
 */
package car.show.pkg12;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yoofiyaapa
 */
public class viewOrder extends javax.swing.JFrame {

    /** Creates new form viewOrder */
    public viewOrder() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        odr = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Order");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(" ORDER DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(439, 20, 218, 29);

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        odr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        odr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order No", "Customer Name", "Car Name", "Car Price", "Bill Amount"
            }
        ));
        odr.setIntercellSpacing(new java.awt.Dimension(1, 7));
        odr.setMinimumSize(new java.awt.Dimension(300, 0));
        odr.setRowHeight(50);
        jScrollPane1.setViewportView(odr);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 80, 980, 360);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("FETCH LIST");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 490, 180, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("HOME PAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(860, 490, 180, 31);

        setSize(new java.awt.Dimension(1072, 572));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();
new Welcome().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DefaultTableModel mdl = (DefaultTableModel) odr.getModel();
        int rowCount = mdl.getRowCount();
        for (int i=1; i<=rowCount; i++){
            mdl.removeRow(0);
        }
            try{
            Class.forName("java.sql.DriverManager");
            Connection con =(Connection) DriverManager.getConnection ("jdbc:mysql://localhost/carshowroom","root","root");
            Statement stmt = con.createStatement();
            String q = "select * from orderlist;",tr=null;
            ResultSet rs = stmt.executeQuery(q);
            while (rs.next()){
                String a,b,c,d,e;
                a = rs.getString("Order_NO");
                b = rs.getString("Customer_Name");
                c = rs.getString("Car_Name");
                d = rs.getString("Car_Price");
                e = rs.getString("Bill");
                Object data[] = {a,b,c,d,e};
                mdl.addRow(data);
                tr = "ss";
            }
            if (tr == null){
                JOptionPane.showMessageDialog(this,"No Order found!");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());  }      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                new viewOrder().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable odr;
    // End of variables declaration//GEN-END:variables
}
